dist: trusty
sudo: false

jobs:
  include:
    - stage: Update test results
      if: type != cron
      install: pip3.6 install junitparser
      script: python3.6 .bin/process.py
    - stage: Clean up
      if: type = cron
      script: bash .bin/clean.sh

notifications:
  email: false

