dist: trusty
sudo: false

jobs:
  include:
    - stage: Update test results
      if: type != cron
      install: 
        - python --version
        - which pip 
        - pip install requests[security]
        - pip install junitparser
      script: python3.6.3 .bin/process.py
    - stage: Clean up
      if: type = cron
      script: bash .bin/clean.sh

notifications:
  email: false

